version: '3'

services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
  ghapis:
    image: ghapis
    env_file:
      - .env
    environment:
      - DB_HOST=db
    build: . 
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db